apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-demo
  template:
    metadata:
      labels:
        app: spring-demo
    spec:
      containers:
      - name: spring-demo
        image: hellisback/k8s-demo-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: spring-demo-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: spring-demo-config
              key: SPRING_DATASOURCE_URL
        - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
          valueFrom:
            configMapKeyRef:
              name: spring-demo-config
              key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: spring-demo-secret
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spring-demo-secret
              key: SPRING_DATASOURCE_PASSWORD
        livenessProbe:
          httpGet:
            path: /demo/actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /demo/actuator/health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 500
---
apiVersion: v1
kind: Service
metadata:
  name: spring-demo-service
spec:
  selector: 
    app: spring-demo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30003
  type: NodePort
