apiVersion: v1
kind: Secret
metadata:
  name: spring-demo-secret
data:
  SPRING_DATASOURCE_USERNAME: ZGVtbw== # base64 encoded value of "demo"
  SPRING_DATASOURCE_PASSWORD: ZGVtbw== # base64 encoded value of "demo"