apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-demo-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SPRING_DATASOURCE_URL: "jdbc:mysql://192.168.49.2:30001/demo?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"